eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://mongodb+srv://admin:22JumpStreet!@atlas-cluster.yuavamy.mongodb.net/?retryWrites=true&w=majority
      host: atlas-cluster.yuavamy.mongodb.net
      port: 27017
      database: orderservicedb
      repositories:
        enables: true


